### ISSUE TITLE
Help wanted: Story Content

### ISSUE THREAD

**Issue by kikotheexile** [kikotheexile/Endless-Sky-Civil-War#101]
As the vast majority of you know, since starting chemotherapy I have been virtually unable to work on this game. Truth is I just feel like total trash all the time. Working on ESS took too much of my willpower even when I was feeling well. 

The shame of it all is that we're so close to being done that we could, theoretically, meet the deadline of August or September first. We just need the story content finished and things like unique fleets expanded on, which honestly shouldn't even be hard. I already have the storyboards made and plans for nearly every aspect of the content, I just can't do it by myself.

I want to publicly thank literally everyone who has worked on ESS, even if the contribution was a simple copy-and-paste fix, and want it to be known that I am neither giving up on nor abandoning the project. I just wanted to be honest with everyone as to why the content suddenly stopped coming from me, and wanted to be honest with myself that I need additional help. 

Thank you for understanding, and thank you for your time.

**Comment by kikotheexile** [comment]
Thanks to the magic of Discord I now have someone working on the Northern Union story, someone working on the Oathkeeper story, and myself - who gets to work on the Republic perspective/victory against the Free Worlds.

**Comment by kikotheexile** [comment]
Dashi, the person taking over the northern union, had their computer get fried
Phil, the person working on the oathkeeper campaign, is struggling with having time to work on the campaign
I had a power outage for a week, while on chemo, while my mom is in hospital, and adopted an orphaned baby bunny, so my work on the rns/fws story has been completely halted until i get my groove back. 

Suffice to say this is going to take longer than expected

**Comment by endlessskymodfan13** [comment]
Whoa kikotheexile, I had no idea about this. I guess I'm new enough that I just never heard or figured this out, let alone knew your mod existed. Thank you for posting in my thread and letting me know about your mod. I hope you feel better soon.
 How does someone on chemo have such kindness and selflessness to adopt a bunny in the middle of all that? Bruh.


I pm'd God with a prayer for you and your mother, and the bunny too.

**Comment by kikotheexile** [comment]
I'm still kicking, and we still need help with story content. 
https://discord.gg/ND788CC

**Comment by kikotheexile** [comment]
Story content is really getting there thanks to Phil, Knight, and everyone's efforts. 

We could still use help, ( https://discord.gg/ND788CC ) but I think we are officially in a state where I can close this issue.
