### ISSUE TITLE
"Escort battle fleet" mission broken. 

### ISSUE THREAD

**Issue by Nightingale093** [kikotheexile/Endless-Sky-Civil-War#145]
as soon as i leave the ships i am escorting break formation and spin endlessly in random directions

**Comment by Nightingale093** [comment]
as soon as you leave the planet where you got the mission the ships you are assigned to escort just spin off in different directions

**Comment by kikotheexile** [comment]
I need to know which story arc this is for. 

If it is for the northern union or republic, both of those are in dire need of revision and fixing as is. 

If it's for the free worlds, that is a problem and i will need to figure out which mission it is and how badly it is broken.

**Comment by Nightingale093** [comment]
its the free worlds one

**Comment by Nightingale093** [comment]
and its game breaking this bug

**Comment by kikotheexile** [comment]
This is probably the line thats broken:
https://github.com/kikotheexile/Endless-Sky-Civil-War/blob/108b3d975eae5828fde70396fc2ec11bc5e3ac20/data/mainplot/story%20free%20worlds.txt#L4602

I corrected that with:
https://github.com/kikotheexile/Endless-Sky-Civil-War/commit/ad74a8c01c0f73c7792434e1121577c6ecebe814

Feel free to update the game and reload save from a couple back (before you pick up the fleet) so the broken data isnt in your save file, then try it again. Should work.

**Comment by Nightingale093** [comment]
ok how do i update my game then?

**Comment by kikotheexile** [comment]
There are several ways to go about this, i would suggest asking members of the discord for more information
