### ISSUE TITLE
Expansion to the current R&D subplot of the Free Worlds storyline

### ISSUE THREAD

**Issue by shitwolfymakes** [kikotheexile/Endless-Sky-Civil-War#17]
Currently, the R&D subplot lacks depth, and only really serves to give the player new weapons after 5 minutes of work:

Meet Barmy->Test Plasma Turret->Get Plasma Turret->Test Flamethrower->Get Flamethrower->Get Capital Ship

Boring. Barmy deserves more screen time. The new structure will look like this:

Bring Hardware to Kraz->Meet Barmy->Plasma Turret Storyline->Get Plasma Turret->Flamethrower Storyline->Get Flamethrower->Capital Ship Testing Storyline->Get Capital Ship

This adds 3 new storylines, to better flesh out the realities of wartime R&D.

### Plasma Turret Storyline
The components you brought to Barmy work, and the plasma turret is ready for an initial live-fire test. Barmy asks the player to help, using the current mission (FW Plasma Testing) with a few tweaks to the dialog. Extensions are as follows:
- When the player returns, Barmy asks them to come back in a few days, to give him time to go over the data from the test. After a few days, Barmy tells the player that the test was successful, but their best coolant system isn't enough to keep the turret operation in a real battle. Given enough time, Barmy could design a new system, or the player could negotiate a contract for an already existing cooling system from Tarazed Corp.
  - Declining to negotiate for the new system gives a delay in the availability, similar to the current delay.
  - Accepting starts a new quest (FW Coolant Negotiations), upon completion, the turrets are immediately available.

- FW Coolant Negotiations: Player heads to Tarazed, and meets a Tarazed Corp. rep there. The rep rejects their initial offer. The player comes back the next day and offers more, but is rejected again. After the rejection, a stranger appears and offers to sell the schematics for a couple million credits.
  - Declining: The player comes back the next day, and the highest offer is finally rejected.
  - Accepting: The player gets a mission to return with the schematics. The schematics are illegal and the player should be attacked by security if caught with them.

### Flamethrower Storyline
After a similar delay to start this mission (FW Flamethrower), The player is summoned to Kraz by Barmy. Barmy asks the player to help test a flamethrower, using the current mission (FW Flamethrower 2) with a few tweaks. Extensions are as follows:
- When the player returns, Barmy asks them to come back in a few days, to give him time to go over the data from the test. After a few days, Barmy tells the player that the test was successful and then new coolant systems worked here too, but it uses too much fuel too quickly. He asks the player to negotiate for a fuel siphon regulator from the Tarazed Corporation.
  - Declining: The current delay before giving the player access to the turret
  - Accepting: Starts a new mission (FW Fuel Siphon Regulator), upon completion, the flamethrowers are immediately available.
- FW Fuel Siphon Regulator: Depends on what the player did the previous mission
  - A) Paid for the parts: Player offers to pay for them, and the offer is accepted
  - B) Stole the schematics: Tarazed has a fleet of enemies that shoot on sight. Once the player kills them or lands, they are charged 4M credits for the Fuel Siphon Regulator. Alternatively, if the player doesn't have the money, they can loot the part from the hostile ships.

### Capital Ship Testing Storyline
About a month after the acquisition of the flamethrowers, the player is contacted by Barmy, and asked to come to Kraz. Upon arriving, Barmy explains that the final test models of the new line of FW warships is complete, and they want to test the integration of the plasma turrets and flamethrowers onto the new ships.
- FW Integration Testing 1: Add test ship as a combat escort with plasma cannons, then go fight a pirate
- FW Integration Testing 2: Add test ship as a combat escort with flamethrowers, then go fight a pirate
- FW Integration Testing 3: Add test ship as a combat escort with plasma cannons and a flamethrower, and a couple Furies with flamethrowers, then go fight a pirate. Upon returning, Barmy thanks you and tells you that the headroom left over is enough for "some big-ass ship the kids over at Southbound are cookin' up"
  - Completing unlocks the ships you've been testing

### Notes
Given that I'm working on ESMB, I don't have time to actually write out the missions, so I need someone to actually do all the writing out. I'd be happy to provide feedback on the details, this is just a rough draft of what the overhauled story should looks like.

**Comment by kikotheexile** [comment]
might be me who does the writing whilst working on the other branches. But it would be nice if it were, ya know, someone else

**Comment by kikotheexile** [comment]
Flamethrower needs reworked (even if it continues to be included)

Electron Beam mission should be included in the Kraz arc, not in the main plot (already removed from mail plot)

**Comment by kikotheexile** [comment]
Kishi on discord has volunteered for this assignment.

**Comment by shitwolfymakes** [comment]
Per the chat on Discord:

> a whole ass development questline for various weapons designs (the plasma turret being refined, experiments with the flame thrower, stealing and attempting to reverse engineer the electron beam) as well as dealing with the plasma cultist Dylan however you want to (preferably by working with her, but she can be the opposition in that mini-arc)

**Comment by kikotheexile** [comment]
No one else wanted to take this job it looks like, so this is now my problem. 

Because this is my problem, there is no reason to keep the issue open, I'll just add it to the Discord Workflow room. 

Closing the issue as... """Resolved"""
